services:
  delta2:
    build:
      context: .
      dockerfile: DOCKERFILE
    user: "root"
    ports:
      - "9000:9000"
    volumes:
      - app:/app
    environment:
      - NAME=Delta2
    network_mode: "host"

  memgraph:
    image: memgraph/memgraph-platform
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    user: "root"
    volumes:
      - app:/app
volumes:
  app:
