services:
  delta2:
    build:
      context: .
      dockerfile: DOCKERFILE
    user: "root"
    privileged: true  # Enable privileged mode
    network_mode: "host"  # Use the host's network stack
    volumes:
      - /:/host  # Mount the entire host filesystem under /host (use with caution)
    environment:
      - NAME=Delta2

  memgraph:
    image: memgraph/memgraph-platform
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    user: "root"
    volumes:
      - app:/app
    networks:
      - "delta2_network"

volumes:
  app:
networks:
  delta2_network:
    driver: bridge

