services:
  delta2:
    build:
      context: .
      dockerfile: DOCKERFILE
    user: "root"
    ports:
      - "9000:9000"
    volumes:
      - app:/app
    environment:
      - NAME=Delta2
    networks: 
      - "delta2_network"

  memgraph:
    image: memgraph/memgraph-platform
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    user: "root"
    volumes:
      - app:/app
    networks: 
      - "delta2_network"
volumes:
  app:
networks:
  delta2_network:
    driver: bridge
