version: '3'

services:
  web:
    build:
      context: .
      dockerfile: DOCKERFILE
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - NAME=Delta2
    network_mode: "host"
